/**
 * Curated world seeds for the gallery screen.
 * GENERATED by `npx vite-node scripts/curate-seeds.ts` — edit that script and
 * re-run it rather than hand-editing entries (descriptions emphasize stable
 * geography over simulated history, so they survive balance changes).
 */
export interface SeedInfo {
  seed: number;
  name: string;
  description: string;
}

export const SEED_GALLERY: SeedInfo[] = [
  {
    seed: 34,
    name: "The Stonecrown Reaches",
    description:
      "A high country of granite peaks and cold passes, threaded by many rivers. All five peoples endure the first decade; its valleys soon crowd with walled towns, and old borders are often contested.",
  },
  {
    seed: 48,
    name: "The Braided Waters",
    description:
      "Low green country braided with running water, crossed by long rivers. All five peoples endure the first decade; its valleys soon crowd with walled towns, and the marches burn with constant war.",
  },
  {
    seed: 79,
    name: "The Thousand Fords",
    description:
      "Low green country braided with running water, threaded by many rivers. All five peoples endure the first decade; its valleys soon crowd with walled towns, and old borders are often contested.",
  },
  {
    seed: 10,
    name: "The Emberfall Heartlands",
    description:
      "Broad temperate heartlands beneath gentle hills, crossed by long rivers. All five peoples endure the first decade; its valleys soon crowd with walled towns, and old borders are often contested.",
  },
  {
    seed: 64,
    name: "The Sundered Isles",
    description:
      "A realm of scattered islands and long sounds, crossed by long rivers. All five peoples endure the first decade; its valleys soon crowd with walled towns, and old borders are often contested.",
  },
  {
    seed: 76,
    name: "The Long Meadows",
    description:
      "Broad temperate heartlands beneath gentle hills. All five peoples endure the first decade; its valleys soon crowd with walled towns, and old borders are often contested.",
  },
  {
    seed: 3,
    name: "The Scattered Shores",
    description:
      "A realm of scattered islands and long sounds, crossed by long rivers. All five peoples endure the first decade; walled towns rise within a generation, and the marches burn with constant war.",
  },
  {
    seed: 89,
    name: "The Deepwood Realm",
    description:
      "A realm swallowed by deep, old forest, crossed by long rivers. All five peoples endure the first decade; walled towns rise within a generation, and old borders are often contested.",
  },
];
